#!/bin/bash

echo "=== PTracker API Routes ==="
echo "Base URL: http://localhost:3001/api/v1"
echo ""
echo "Authentication Routes:"
echo "  POST   /api/v1/auth/register"
echo "  POST   /api/v1/auth/login"
echo "  POST   /api/v1/auth/logout"
echo "  POST   /api/v1/auth/refresh"
echo "  POST   /api/v1/auth/forgot-password"
echo "  POST   /api/v1/auth/reset-password"
echo "  POST   /api/v1/auth/verify-email"
echo "  POST   /api/v1/auth/resend-verification"
echo "  GET    /api/v1/auth/profile"
echo "  GET    /api/v1/auth/google"
echo "  GET    /api/v1/auth/google/callback"
echo "  GET    /api/v1/auth/facebook"
echo "  GET    /api/v1/auth/facebook/callback"
echo "  GET    /api/v1/auth/telegram"
echo "  POST   /api/v1/auth/telegram"
echo "  POST   /api/v1/auth/wallet/connect"
echo "  POST   /api/v1/auth/2fa/enable"
echo "  POST   /api/v1/auth/2fa/disable"
echo "  POST   /api/v1/auth/2fa/verify"
echo ""
echo "User Routes:"
echo "  GET    /api/v1/users"
echo "  GET    /api/v1/users/:id"
echo "  PATCH  /api/v1/users/:id"
echo "  DELETE /api/v1/users/:id"
echo ""
echo "Portfolio Routes:"
echo "  GET    /api/v1/portfolios"
echo "  POST   /api/v1/portfolios"
echo "  GET    /api/v1/portfolios/:id"
echo "  PATCH  /api/v1/portfolios/:id"
echo "  DELETE /api/v1/portfolios/:id"
echo ""
echo "Transaction Routes:"
echo "  GET    /api/v1/transactions"
echo "  POST   /api/v1/transactions"
echo "  GET    /api/v1/transactions/:id"
echo "  PATCH  /api/v1/transactions/:id"
echo "  DELETE /api/v1/transactions/:id"
echo ""
echo "Market Data Routes:"
echo "  GET    /api/v1/market-data/prices"
echo "  GET    /api/v1/market-data/prices/:symbol"
echo "  GET    /api/v1/market-data/trending"
echo "  GET    /api/v1/market-data/historical/:symbol"
echo ""
echo "Health Check:"
echo "  GET    /api/v1/health"
echo ""
echo "Documentation:"
echo "  GET    /api/docs (Swagger UI)"
echo ""